# Header
menu:
  HOME: /
  JAVASCRIPT: /categories/javascript
  ALGORITHM: /categories/Algorithm
  ARCHIVES: /archives

# Content
excerpt_link: ......
fancybox: false

# Sidebar
sidebar:
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:

# Miscellaneous
google_analytics: UA-103254205-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# scrollUp 样式
scrollUp: image


# Comment
comment:
    disqus: [shldhee]
